appPort: ":80"
mongoDbUser: "user"
mongoDbPass: "pass"
mongoDbDatabaseName: "spectra"
mongoDbHost: "mongo_espectra"
mongoDbPort: "27017"
maxPoolSize: "20"
authControlHost: "http://auth_control/api/v1"
