appPort: ":3003"
mongoDbUser: "user"
mongoDbPass: "pass"
mongoDbDatabaseName: "spectra"
mongoDbHost: "localhost"
mongoDbPort: "27017"
maxPoolSize: "20"
authControlHost: "http://localhost:3002/api/v1"
