---
version: '3'

services:
    postgres-db:
        image: postgres
        container_name: "postgres-db"
        environment:
            - POSTGRES_PASSWORD=pass
            - POSTGRES_USER=user
            - POSTGRES_DB=database
        restart: on-failure
        ports:
            - "5432:5432"

    enroll:
        build: .
        container_name: "enroll"
        ports:
            - "3003:80"
        depends_on:
            - postgres-db
